version: "3.8"
services:
  app:
    build: .
    ports:
      - 8089:8089
    image: mali/notbad
    command: [ "python3", "-m" , "flask", "run", "--host=0.0.0.0", "--port=8089", "--debug"]
    volumes:
      - ./src:/python-docker