apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notbad-ingress
  namespace: notbad
  annotations:
    kubernetes.io/ingress.class: public
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: notbad
                port:
                  number: 8089